name = "titan trip line hook handler"
main = "src/index.ts"
compatibility_date = "2023-03-22"

[vars]
GPT_MODEL = "gpt-3.5-turbo"


kv_namespaces = [
  { binding = "GPT", id = "2bcb7e5d9ba34a789245ad8a197dc2e7" }
]